spring:
  config:
    activate:
      on-profile: prod
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/hello-member-db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23ctOZWLeVONhbRCN6
            client-secret: ${SPRING_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET}
            redirect-uri: "http://hello.hyunbindev.site/login/oauth2/code/{registrationId}"
            client-name: GitHub
      provider:
        github:
          authorization-uri: https://github.com/login/oauth/authorize
          token-uri: https://github.com/login/oauth/access_token
          user-info-uri: https://api.github.com/user
          user-name-attribute: login
  jwt:
    key: ${SPRING_JWT_KEY}
    term: 86400000