apiVersion: v1
kind: Service
metadata:
  name: hello-member-ms-service
  namespace: hello-app
spec:
  selector:
    app: hello-member-ms
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP