server:
  port: 8081
spring:
  config:
    activate:
      on-profile: prod
  jwt:
    key: ${SPRING_JWT_KEY}
  application:
    name: hellogateway
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  cloud:
    gateway:
      default-filters:
       - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: oauth2_route
          uri: http://hello-member-ms.hello-app.svc.cluster.local:8080
          predicates:
            - Path=/oauth2/**, /login/oauth2/code/github
        - id: member_route
          uri: http://hello-member-ms.hello-app.svc.cluster.local:8080
          predicates:
            - Path=/api/member/**
        - id: feed_route
          uri: http://hello-feed-ms.hello-app.svc.cluster.local:8082
          predicates:
            - Path=/api/feed/**