spring:
  config:
    activate:
      on-profile: prod
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://hello-feed-db-service.hello-app.svc.cluster.local:3306/hellofeed?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
app:
  service:
    member: "http://hello-member-ms.hello-app.svc.cluster.local:8080"
